---
- name: Make requests to morpheus api
  hosts: localhost
  connection: local
  vars:
    morpheus_appliance_url: https://devlmorph001.techlab.com/api/service-plans
    morpheus_api_token: fa74c6c7-aee5-4389-906b-51967bd616b0
  tasks:
    - name: Create a Service Plan for Polaris-small
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-s
          code: Polsmall
          displayorder: "1"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "1"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans
    - debug:
        msg: "{{ serviceplans }}"

    - name: Create a Service Plan for Polaris-smallmed
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-sm
          code: Polsm
          displayorder: "2"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "2"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans1
    - debug:
        msg: "{{ serviceplans1 }}"
    
    - name: Create a Service Plan for Polaris-med
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-med
          code: Polmed
          displayorder: "3"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "1"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans1
    - debug:
        msg: "{{ serviceplans1 }}"
        
    - name: Create a Service Plan for Polaris-highmed
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-highmed
          code: PolHm
          displayorder: "4"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "1"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans1
    - debug:
        msg: "{{ serviceplans1 }}"
        
    - name: Create a Service Plan for Polaris-large
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-large
          code: Pollarge
          displayorder: "5"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "1"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans1
    - debug:
        msg: "{{ serviceplans1 }}"
    
    - name: Create a Service Plan for Polaris-extralarge
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body:
          name: Polaris-XL
          code: PolXL
          displayorder: "6"
          storage: "30720"
          provision type: vm ware
          memory: "8192"
          corecount: "1"
          config:
            maxStorage: "102400"
            minStorage: "8192"
            maxMemory: "102400"
            minMemory: "8192"
            maxCore: "2"
            minCore: "1"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans1
    - debug:
        msg: "{{ serviceplans1 }}"
 
