---
- name: Make create requests to morpheus api
  hosts: localhost
  connection: local
  vars:
    morpheus_appliance_url: https://devlmorph001.techlab.com/api/service-plans
    morpheus_api_token: ####
    
  roles:
    - create-a-tag-service-plans
- import_playbook: main.yml
  when: size == 'polsmall'
  
- import_playbook: main1.yml
  when: size == 'polmed'
