---
- name: Make requests to morpheus api
  hosts: localhost
  connection: local
  vars:
    morpheus_appliance_url: https://api.gomorpheus.com/api/service-plans
    morpheus_api_token: fa74c6c7-aee5-4389-906b-51967bd616b0
- name: Create a Service Plan for Polaris-small
  job_template_structure:
    name: Polaris-small
    code: Polsmall
    displayorder: 1
    storage: 30720
    provision type: vm ware
    memory: 8192
    corecount: 1
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 102400
      minMemory: 8192
      maxCore: 2
      minCore: 1
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans

- name: Create a Service Plan for Polaris-small high mem
  job_template_structure:
    name: Polaris-small high mem
    code: PolsmallHM
    displayorder: 2
    storage: 81920
    provision type: vm ware
    memory: 16384
    corecount: 1
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 16384
      minMemory: 4096
      maxCore: 2
      minCore: 1
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans

- name: Create a Service Plan for Polaris-medium
  job_template_structure:
    name: Polaris-medium
    code: PolMed
    displayorder: 3
    storage: 102400
    provision type: vm ware
    memory: 8192
    corecount: 4
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 16384
      minMemory: 4096
      maxCore: 4
      minCore: 1
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans

- name: Create a Service Plan for Polaris-high medium
  job_template_structure:
    name: Polaris-high medium
    code: PolMedHM
    displayorder: 4
    storage: 102400
    provision type: vm ware
    memory: 16384
    corecount: 4
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 16384
      minMemory: 8192
      maxCore: 4
      minCore: 1
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans

- name: Create a Service Plan for Polariss-Large
  job_template_structure:
    name: Polariss-Large
    code: Pollarge
    displayorder: 5
    storage: 102400
    provision type: vm ware
    memory: 16384
    corecount: 8
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 16384
      minMemory: 8192
      maxCore: 8
      minCore: 4
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans

- name: Create a Service Plan for Polariss-XLarge
  job_template_structure:
    name: Polariss-XLarge
    code: PolXL
    displayorder: 6
    storage: 102400
    provision type: vm ware
    memory: 32768
    corecount: 8
    config:
      maxStorage: 102400
      minStorage: 8192
      maxMemory: 32768
      minMemory: 8192
      maxCore: 8
      minCore: 4
  uri:
    url: '{{ morpheus_appliance_url }}/api/service-plans'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
        Content-Type: "application/json"
    method: POST
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: morpheus_service-plans
