---
- name: deactivate a servicePlan
  hosts: localhost
  connection: local
  vars:
    morpheus_appliance_url: https://api.gomorpheus.com/api/service-plans:id/deactivate
    morpheus_api_token: fa74c6c7-aee5-4389-906b-51967bd616b0
  tasks:
    - name: polaris
      uri:
        url: "{{ morpheus_appliance_url}}"
        headers:
            Authorization: "BEARER {{ morpheus_api_token }}"
        method: POST
        body:
          servicePlan:
            success: true
        validate_certs: false
        body_format: json
        force_basic_auth: yes
        return_content: true
      register: deactivated_service_plans
    - debug:
       msg: "{{ deactivated_service_plans}}"
