- name: Make requests to example api
  hosts: localhost
  connection: local
  tasks:
    - name: list contents
      uri:
        method: GET
        url: "https://devlmorph001.techlab.com/login/account/1/"
        return_content: yes
        headers:
          Accept: application/json
      register: response

    - debug:
        msg: "{{ response.content }}"
