- name: Make requests to example api
  hosts: localhost
  connection: local
  tasks:
    - name: list contents
      uri:
        method: GET
        url: '{{ morpheus_appliance_url }}/api/groups?name={{ group_name | urlencode }}'
        return_content: yes
        headers:
          Accept: application/json
      register: response

    - debug:
        msg: "{{ response.content }}"
