---
- name: Make requests to morpheus api
  hosts: localhost
  connection: local
  vars:
    morpheus_appliance_url: https://devlmorph001.techlab.com/api/service-plans
    morpheus_api_token: fa74c6c7-aee5-4389-906b-51967bd616b0
  tasks:
    - name: Create a Service Plan for Polaris-small
      uri:
        method: POST
        url: '{{ morpheus_appliance_url }}'
        headers:
          Authorization: "BEARER {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body: "{{ lookup('file','crserviceplan.json') }}"
        force_basic_auth: yes
        return_content: true
        validate_certs: no
      register: serviceplans
    - debug:
        msg: "{{ serviceplans }}"
