---
- name: activate a service plan
  uri:
    method: PUT
    url: '{{ morpheus_appliance_url }}'
    headers:
      Authorization: "BEARER {{ morpheus_api_token }}"
    force_basic_auth: no
    return_content: true
    validate_certs: no
  register: activatedserviceplans
- debug:
    msg: "{{ activatedserviceplans }}"
