---
- name: activate a service plan
  uri:
    method: POST
    url: '{{ morpheus_appliance_url }}'
    headers:
      Authorization: "BEARER {{ morpheus_api_token }}"
      Content-Type: "application/json"
    force_basic_auth: yes
    return_content: true
    status_code: -1
    validate_certs: no
  register: updatedserviceplans
  success: true
- debug:
    msg: "{{ activatedserviceplans }}"
