---
- name: activate a service plan
  uri:
    method: PUT
    url: '{{ morpheus_appliance_url }}/{{ idtoactivate }}/activate' #ansible-playbook activate-a-service-plan.yml -e '{"idtoactivate": id}'
    headers:
      Authorization: "BEARER {{ morpheus_api_token }}"
    return_content: true
    validate_certs: no
  register: activatedserviceplans
- debug:
    msg: "{{ activatedserviceplans }}"
