---
  - name: create-a-small-plan
    uri:
      method: POST
      url: '{{ morpheus_appliance_url }}'
      body_format: json
      headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
      body: "{{ lookup('file','crserviceplan.json') }}"
      force_basic_auth: no
      return_content: true
      validate_certs: no
    register: serviceplans
    when: "{{ (size) == 'ps' or (size) == 'all' }}"

  - name: create-a-medium-plan
    uri:
      method: POST
      url: '{{ morpheus_appliance_url }}'
      body_format: json
      headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
      body: "{{ lookup('file','crserviceplan.json') }}"
      force_basic_auth: no
      return_content: true
      validate_certs: no
    register: serviceplans
    when: "{{ (size) == 'pm' or (size) == 'all' }}"

  - name: create-a-highmedium-plan
    uri:
      method: POST
      url: '{{ morpheus_appliance_url }}'
      body_format: json
      headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
      body: "{{ lookup('file','crserviceplan.json') }}"
      force_basic_auth: no
      return_content: true
      validate_certs: no
    register: serviceplans
    when: "{{ (size) == 'phm' or (size) == 'all' }}"
    
  - name: create-a-medium-plan
    uri:
      method: POST
      url: '{{ morpheus_appliance_url }}'
      body_format: json
      headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
      body: "{{ lookup('file','crserviceplan.json') }}"
      force_basic_auth: no
      return_content: true
      validate_certs: no
    register: serviceplans
    when: "{{ (size) == 'pmed' or (size) == 'all' }}"

  - name: create-a-large-plan
    uri:
      method: POST
      url: '{{ morpheus_appliance_url }}'
      body_format: json
      headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
      body: "{{ lookup('file','crserviceplan.json') }}"
      force_basic_auth: no
      return_content: true
      validate_certs: no
    register: serviceplans
    when: "{{ (size) == 'pl' or (size) == 'all' }}"
    
