---
- name: update a Service Plan for Polaris-small  
  uri:
    method: PUT
    url: '{{ morpheus_appliance_url }}/{{ idtoupdate }}' #ansible-playbook update-a-service-plan.yml -e '{"idtoupdate": id}'
    body_format: json
    headers:
      Authorization: "BEARER {{ morpheus_api_token }}"
    body: "{{ lookup('file','updateservice.json') }}"
    force_basic_auth: no
    return_content: true
    validate_certs: no
  register: updated_serviceplans
- debug:
    msg: "{{ updated_serviceplans }}"
