---
- name: update a Service Plan for Polaris-small
  uri:
    method: POST
    url: '{{ morpheus_appliance_url }}'
    headers:
      Authorization: "BEARER {{ morpheus_api_token }}"
      Content-Type: "application/json"
    body:
      name: Polaris-smallmed
      code: Polsm
      displayorder: "3"
      storage: "30720"
      provision type: vm ware
      memory: "8192"
      corecount: "1"
      config:
        maxStorage: "102400"
        minStorage: "8192"
        maxMemory: "102400"
        minMemory: "8192"
        maxCore: "2"
        minCore: "1"
    force_basic_auth: yes
    return_content: true
    status_code: -1
    validate_certs: no
  register: updated-serviceplans
- debug:
    msg: "{{ updated-serviceplans }}"
